const path = require('path');
const fs = require('fs');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const { sendEmail } = require('../services/mailer');
const { generatePDF } = require('../services/reportGenerator');

// Mock data generator
const generateSampleFeedback = (deptId, questions) => {
    const feedbacks = [];
    const now = new Date();
    for (let i = 0; i < 5; i++) {
        const answers = new Map();
        questions.forEach(q => {
            let answer = '';
            if (q.type === 'smiley') {
                const options = ['good', 'average', 'bad'];
                answer = options[Math.floor(Math.random() * options.length)];
            }
            else if (q.type === 'rating_5') {
                answer = (Math.floor(Math.random() * 5) + 1).toString();
            }
            else if (q.type === 'text') {
                const texts = [
                    'Great experience overall.',
                    'Could be better.',
                    'Staff was very helpful.',
                    'Cleanliness needs improvement.',
                    'No comments.'
                ];
                answer = texts[Math.floor(Math.random() * texts.length)];
            }

            answers.set(q.id, answer);
        });

        feedbacks.push({
            submittedAt: new Date(now.getTime() - Math.floor(Math.random() * 7 * 24 * 60 * 60 * 1000)), // Random time in last week
            departmentId: deptId,
            answers: answers,
            name: Math.random() > 0.5 ? 'John Doe' : 'Anonymous',
            email: 'john@example.com'
        });
    }
    return feedbacks;
};

const run = async () => {
    try {
        const questionsConfigPath = path.join(__dirname, '../../config/questions.json');

        if (!fs.existsSync(questionsConfigPath)) {
            throw new Error(`Config not found at ${questionsConfigPath}`);
        }

        const questionsConfig = JSON.parse(fs.readFileSync(questionsConfigPath, 'utf8'));
        const targetEmail = 'aryalsujay@gmail.com';

        console.log(`Starting test email sequence to ${targetEmail}...`);

        for (const [deptId, config] of Object.entries(questionsConfig)) {
            console.log(`Generating report for ${config.name} (${deptId})...`);

            const questions = config.questions;
            const feedbacks = generateSampleFeedback(deptId, questions);

            const pdfBuffer = await generatePDF(config.name, feedbacks, questions);

            // Email Body (Summary)
            let html = `<h1>TEST Weekly Feedback Report: ${config.name}</h1>`;
            html += `<p>This is a TEST email generated by the system to verify layout and content.</p>`;
            html += `<p><b>Period:</b> ${new Date(new Date().setDate(new Date().getDate() - 7)).toDateString()} - ${new Date().toDateString()}</p>`;
            html += `<p><b>Total Submissions:</b> ${feedbacks.length}</p>`;
            html += `<hr/>`;
            html += `<p><i>Global Pagoda Feedback System</i></p>`;

            console.log(`Sending email...`);
            await sendEmail([targetEmail], `TEST Weekly Report - ${config.name}`, html, [
                {
                    filename: `TEST_Feedback_Report_${deptId}.pdf`,
                    content: pdfBuffer
                }
            ]);
            console.log(`Email sent for ${deptId}`);
        }
        console.log('All test emails sent successfully.');
        process.exit(0);
    } catch (error) {
        console.error('Error in test script:', error);
        process.exit(1);
    }
};

run();
